name: CI

on:
  push:
    branches: [ riscv ]
  pull_request:
    branches: [ riscv ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: get binutils-riscv64-linux-gnu
      run: sudo apt-get install binutils-riscv64-linux-gnu

    - name: build 
      run: make clean;make alt; make clean; make
